(() => {
  'use strict';

  const STORAGE_KEY='every-cent-money-tracker-v1';
  const CACHE_KEY='genevieve-cloud-revision-v2';
  const nativeSetItem=Storage.prototype.setItem;
  const nativeGetItem=Storage.prototype.getItem;
  let revision=Number(nativeGetItem.call(localStorage,CACHE_KEY)||0),saveTimer=null,saving=false,dirty=false,cloudReady=false;

  brandPage();
  showHomeEntry().then(start);

  function brandPage(){
    document.title='Genevieve App — Budget App';
    const theme=document.querySelector('meta[name="theme-color"]'); if(theme)theme.content='#3b0b14';
    const desc=document.querySelector('meta[name="description"]'); if(desc)desc.content='Genevieve App Budget App — personal budgeting, expenses, bills, savings and waste review.';
    addLink('icon','/assets/genevieve-roots-logo.webp'); addLink('apple-touch-icon','/icon-192.png');
    const apple=document.createElement('meta');apple.name='apple-mobile-web-app-title';apple.content='Genevieve Budget';document.head.appendChild(apple);
  }
  function addLink(rel,href){if(document.querySelector(`link[rel="${rel}"]`))return;const l=document.createElement('link');l.rel=rel;l.href=href;document.head.appendChild(l);}
  function showHomeEntry(){return new Promise(resolve=>{
    const gate=document.createElement('div');gate.className='genevieve-lock';gate.setAttribute('aria-label','Open Genevieve Budget App');gate.innerHTML=`<div class="genevieve-lock-card entry-card"><img class="gate-logo" src="/assets/genevieve-roots-logo.webp" alt="Genevieve Roots of Every Journey logo"><div style="font:800 .66rem/1.2 ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:.18em;color:#c9a227">PERSONAL MONEY</div><h2>Genevieve App</h2><div style="color:#fff8e8;font:500 1.05rem Georgia,serif;letter-spacing:.14em;text-transform:uppercase">Budget App</div><p>Budget · expenses · bills · savings · waste review</p><p style="font-family:'Snell Roundhand','Brush Script MT','Segoe Script',cursive;color:#e8cf78;font-size:1.2rem">Safety from roots to every journey</p><button id="openBudgetApp" type="button">Open my Budget App</button></div>`;document.body.appendChild(gate);const btn=gate.querySelector('#openBudgetApp');btn.onclick=()=>{btn.disabled=true;gate.style.opacity='0';gate.style.transition='opacity .22s ease';setTimeout(()=>{gate.remove();resolve();},220)};requestAnimationFrame(()=>btn.focus({preventScroll:true}));
  });}
  function localState(){try{return JSON.parse(nativeGetItem.call(localStorage,STORAGE_KEY)||'null')}catch{return null}}
  function hasMoneyData(s){return !!s&&['accounts','transactions','subscriptions','bills','goals'].some(k=>Array.isArray(s[k])&&s[k].length)||!!(s&&s.budgets&&Object.keys(s.budgets).length);}
  async function api(path,options={}){const res=await fetch('/api/'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body={};try{body=await res.json()}catch{}if(!res.ok){const e=new Error(body.error||'Request failed');e.status=res.status;e.body=body;throw e}return body}
  async function start(){try{const status=await api('status');if(!status.configured)await showSetup();else if(!status.authenticated)await showLogin();await reconcile();installStorageSync();cloudReady=true;setCloudStatus('ok','Saved online')}catch(error){console.warn('Genevieve cloud saving unavailable; using private device storage.',error);setCloudStatus('','Private on this device')}finally{loadBudgetApp()}}
  async function reconcile(){const remote=await api('state');revision=Number(remote.revision)||0;nativeSetItem.call(localStorage,CACHE_KEY,String(revision));const local=localState(),remoteState=remote.state&&typeof remote.state==='object'?remote.state:null;if(hasMoneyData(remoteState)){nativeSetItem.call(localStorage,STORAGE_KEY,JSON.stringify(remoteState));return}if(hasMoneyData(local)){const saved=await api('state',{method:'PUT',body:JSON.stringify({state:local,revision})});revision=Number(saved.revision)||revision+1;nativeSetItem.call(localStorage,CACHE_KEY,String(revision));return}if(remoteState)nativeSetItem.call(localStorage,STORAGE_KEY,JSON.stringify(remoteState));}
  function installStorageSync(){Storage.prototype.setItem=function(key,value){nativeSetItem.call(this,key,value);if(this===localStorage&&key===STORAGE_KEY&&cloudReady)queueCloudSave()};window.addEventListener('online',()=>{if(dirty&&cloudReady)saveNow()});}
  function queueCloudSave(){dirty=true;setCloudStatus('','Saving…');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,350)}
  async function saveNow(){if(saving||!dirty||!cloudReady)return;saving=true;dirty=false;try{const result=await api('state',{method:'PUT',body:JSON.stringify({state:localState(),revision})});revision=Number(result.revision)||revision+1;nativeSetItem.call(localStorage,CACHE_KEY,String(revision));setCloudStatus('ok','Saved online')}catch(error){if(error.status===409){try{const remote=await api('state');revision=Number(remote.revision)||revision;dirty=true}catch{}}else{dirty=true;cloudReady=false;setCloudStatus('','Private on this device')}}finally{saving=false;if(dirty&&cloudReady)setTimeout(saveNow,800)}}
  function setCloudStatus(kind,text){let pill=document.getElementById('genevieveCloudPill');if(!pill){pill=document.createElement('div');pill.id='genevieveCloudPill';pill.className='cloud-pill';pill.innerHTML='<span class="cloud-dot"></span><span></span>';document.body.appendChild(pill)}pill.querySelector('.cloud-dot').className='cloud-dot '+(kind||'');pill.querySelector('span:last-child').textContent=text}
  function showSetup(){return showGate('Secure setup','<label>Private setup code<input id="gvSetupCode" autocomplete="one-time-code" required></label><label>Create a PIN/password<input id="gvSetupPassword" type="password" minlength="6" autocomplete="new-password" required></label>','Set up Budget App',async()=>{await api('setup',{method:'POST',body:JSON.stringify({setupCode:document.getElementById('gvSetupCode').value,password:document.getElementById('gvSetupPassword').value})})})}
  function showLogin(){return showGate('Welcome back','<label>Your PIN/password<input id="gvLoginPassword" type="password" autocomplete="current-password" required></label>','Open Budget App',async()=>{await api('login',{method:'POST',body:JSON.stringify({password:document.getElementById('gvLoginPassword').value})})})}
  function showGate(title,fields,buttonText,action){return new Promise(resolve=>{const gate=document.createElement('div');gate.className='genevieve-lock';gate.innerHTML=`<div class="genevieve-lock-card"><img class="gate-logo" src="/assets/genevieve-roots-logo.webp" alt="Genevieve tree and roots logo"><div style="font-size:.65rem;font-weight:900;letter-spacing:.16em;color:#c9a227">GENEVIEVE APP</div><h2>${title}</h2><p>Budget App · Safety from roots to every journey</p><form>${fields}<div class="error"></div><button>${buttonText}</button></form></div>`;document.body.appendChild(gate);const form=gate.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();const err=gate.querySelector('.error'),button=gate.querySelector('button');err.textContent='';button.disabled=true;button.textContent='Connecting…';try{await action();gate.remove();resolve()}catch(error){err.textContent=error.message;button.disabled=false;button.textContent=buttonText}})})}
  function loadBudgetApp(){if(window.__genevieveBudgetLoaded)return;window.__genevieveBudgetLoaded=true;const script=document.createElement('script');script.src='/legacy-app.js?v=budget-maroon-2';script.onload=()=>document.dispatchEvent(new Event('DOMContentLoaded',{bubbles:true}));document.body.appendChild(script)}
})();
